### ISSUE TITLE
Error callback invoked twice

### ISSUE THREAD

**Issue by haraldrudell** [agsh/onvif#116]
Because onvif is not implemented as promises, in certain situations the callback is invoked twice

if an error is provoked: ```new Cam({hostname: '%%'}, e => console.error('X', e))``` one can  immediately see that the callback is invoked twice with similar but not identical errors

This is because in **lib/cam.js:105**, if **getSystemDateAndTime** fails, **getCapabilities** is invoked anyway

There is a strategic decision to be taken whether **getSystemDateAndTime** should be allowed to fail, and if that is only a warning or a fatal error

If old-style callbacks is to be used, a flag will be required so that the callback is not invoked twice

Better still would be to use async functions, in which the underlying promise takes care of multiple invocations

**Comment by RogerHardiman** [comment]
@haraldrudell wrote "If old-style callbacks is to be used, a flag will be required so that the callback is not invoked twice"

The flag was there. It is called `errCall`. What I found was a bug where the flag was not set to true properly which allowed the 2nd callback to execute.
This is fixed in my 'roger' branch with a Pull Request to master ready to merge.
