### ISSUE TITLE
npm tests do not exit due to events loop

### ISSUE THREAD

**Issue by RogerHardiman** [agsh/onvif#126]
I'm sure I've seen a case during development where npm tests remains running polling the serverMockup for events even when the test should have finished.

I need to try and re-create it here but just wanted to leave an issue to remind myself

**Comment by agsh** [comment]
This is probably because tcp and udp sockets never closed explicit.
I added implicit closing via `.unref` method here: https://github.com/agsh/onvif/blob/0675e8ae14991ed98c8cbdf15964f46aef15d384/test/serverMockup.coffee#L72
Obviously I should rewrite tests. And also do it in js or ts instead of coffeescript :)

**Comment by RogerHardiman** [comment]
I'd noticed the unrefs. That is a good idea.

I think the problem is that even when you stop listening for events the background worker that continually does Pulls from the camera keeps running.
It is intermittent. Some times it works on my Linux box. Some times it keeps pulling even after you have told it to stop.
I think the problem is a race condition and timings in the events.coffee.
I noticed the timeouts are 30ms so perhaps that is too short.

**Comment by RogerHardiman** [comment]
All fixed now
