### ISSUE TITLE
ONVIF Soap Fault: Error 401: HTTP 401 Unauthorized (Fuluva camera)

### ISSUE THREAD

**Issue by kjlaw89** [agsh/onvif#178]
I'm currently having any issue authenticating with an ONVIF camera. The camera in question is a Fuluva A-Series camera (http://fuluva.cn/A-DFQ610-5MP-POE.html). It's not much, but here are the details I'm using when connecting:

> Cam {
>   hostname: '192.168.112.129',
>   username: 'admin',
>   password: '123456',
>   port: 80,
>   path: '/onvif/device_service',
>   timeout: 120000,
>   agent: false,
>   preserveAddress: true,
>   events: {} }
> Error: ONVIF SOAP Fault: Error 401: HTTP 401 Unauthorized
>     at /path/node_modules/onvif/lib/utils.js:91:13
>     at Parser.<anonymous> (/path/node_modules/onvif/node_modules/xml2js/lib/parser.js:304:18)
>     at emitOne (events.js:96:13)
>     at Parser.emit (events.js:188:7)
>     at Object.onclosetag (/path/node_modules/onvif/node_modules/xml2js/lib/parser.js:262:26)
>     at emit (/path/node_modules/sax/lib/sax.js:639:35)
>     at emitNode (/path/node_modules/sax/lib/sax.js:644:5)
>     at closeTag (/path/node_modules/sax/lib/sax.js:903:7)
>     at Object.write (/path/node_modules/sax/lib/sax.js:1444:13)
>     at Parser.exports.Parser.Parser.parseString (/path/node_modules/onvif/node_modules/xml2js/lib/parser.js:323:31)

I've verified that ONVIF is enabled for the camera and also made sure the camera's time was correct. We've used this library for connecting to other cameras so I know the code itself is fine.

I also attempted this process with the popular [go onvif](https://github.com/use-go/onvif) library and it was able to connect and authenticate (verified by disabling the authenticating and getting back a 401 as a result), so there must be some difference there.

If you need any other details, let me know. I'd be happy to get the results back from the camera if it'd assist, just need to know where to put the appropriate logging.

**Comment by agsh** [comment]
Hello! For now I think that this is an error with http headers that caused unauthorised response, but I can be mistaken. If you can grab the http requests via wireshark form go-onvif and onvif, this will be greate to compare, what's the difference.

**Comment by agsh** [comment]
Hello! For now I think that this is an error with http headers that caused unauthorised response, but I can be mistaken. If you can grab the http requests via wireshark form go-onvif and onvif, this will be great to compare, what's the difference.

**Comment by kjlaw89** [comment]
This is a headless Linux setup, so I used `tcpdump` to get the data. Hopefully it contains what you're looking for:

Go:     https://gist.github.com/kjlaw89/02472f85f9e7c2581af9830100f19708
Node: https://gist.github.com/kjlaw89/553d8d3bd3b3b44ac7955b876006ca1f

One thing I noticed is it looks like the Node ONVIF library attempts to request the DateAndTime as part of its initial request,  but this camera returns back a 401 Unauthorized for the attempt.

Hopefully this helps! Let me know if you need anything else!

**Comment by kjlaw89** [comment]
Hey @agsh I was just curious if you've had a chance to review. Do you need any more information from me or need to to test any changes?

**Comment by agsh** [comment]
@kjlaw89 Hi! Can you change locally here https://github.com/agsh/onvif/blob/2cdafa0130758a31a7c97df0b3c53d50a2f86d15/lib/cam.js#L327
these lines:
```js
'<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">' +
'<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">' +
'<GetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl"/>' +
'</s:Body>' +
'</s:Envelope>'
```
to these:
```js
this._envelopeHeader() +
'<GetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl"/>' +
this._envelopeFooter()
```
And test it.
This will add auth headers to getSystemDateAndTime request. It seems strange for me to this cam, because it the ONVIF spec, as I remember this request doesn't need auth at all.

**Comment by RogerHardiman** [comment]
I've found quite a lot of cameras that require authentication on getSystemDateAndTime, even though it is not required in the specification. You are supposed to know the far end camera time so that you can adjust the time offset when sending Auth Headers for cameras that have an incorrect clock, (ie not synced to a NTP time source and the camera's clock is wrong). But the industry seems to accept that you must have a camera synced to the right time and you must have authentication on this ONVIF command

**Comment by kjlaw89** [comment]
@agsh That seems to have worked. I'm getting some "Unrecognized configuration" errors with this camera, but that doesn't seem to be stopping it from functioning. I am no longer getting the 401 Unauthorized error though, so that's a plus!

**Comment by agsh** [comment]
@RogerHardiman Thanks for explanation!
@kjlaw89 I've added auth headers into this method in master and v0.6.4

**Comment by RogerHardiman** [comment]
I've just hit the same problem and can tell you what the actual problem was.

This library sends a getSystemDateAndTime command with NO authentication. This is part of the ONVIF spec.
If it fails, with an unathorized command, it re-sends it WITH the authentication.

The bug was that the library checked if the ASCII string that came back from the camera had the words "sender not authorized". That is what it matched.
But my Hik Camera, and the camera in the bug report sent a different string, they send "Unathorized"

The ASCII String match failed and the library did not re-send the command with authentication.

The quick fix is to look for "sender not authorized" and for "unauthorized"
But the better fix is to look for the HTTP Status Code returned which will be a 401.

I've just fixed this properly in my 'roger' branch of the library.

The reason for the two step approach of doing getSystemDateAndTIme with no authentication first is for Axis cameras.
They implement replay attack protection and if your your camera or your computer is not synced to the correct time properly, you will fail to connect to an Axis camera if you always send authentication due to TimeSent: differences.
So for Axis you do getSystemDateAndTime with no password first, as per the ONVIF Spec.

So the fix originally posted was good - it sent authentication.
But the proper fix is to detect the 401 error and not to parse ASCII strings
