### ISSUE TITLE
Bad discovery message not handled in examples

### ISSUE THREAD

**Issue by RogerHardiman** [agsh/onvif#189]
Hi
Had an install where an unknown make of NAS drive responded to the ONVIF Discovery probe.
This library realised it could not process the XML reply and tried to emit the Discovery 'error' event.
However the example code and the README don't mention adding a on('error') handler for discovery.

I am not 100% we even want to tell the user of the library that discovery had a problem, but maybe the places where it emits an 'error' event for Discovery should check for any subscribers before they emit the 'error' event.

I can probably pick this up myself in the future but wanted to record the Issue now so I don't forget it.

**Comment by chriswiggins** [comment]
I think best to add to the README and let the user decide if they want to ignore the error. There could be cases where a legitimate error is thrown and someone would want to catch that (ie a camera with new firmware responding with different XML)

Just my 2c

**Comment by RogerHardiman** [comment]
I agree. Thanks Chris

**Comment by RogerHardiman** [comment]
Have added Error handler and updated Documentation.

For reference if there is no 'error' handler, you get
```
events.js:305
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Wrong SOAP message from 192.168.1.236:60188')
    at EventEmitter.emit (events.js:303:17)
    at /mnt/c/Users/roger/source/onvif/lib/discovery.js:108:15
    at parseSOAPString (/mnt/c/Users/roger/source/onvif/lib/utils.js:108:3)
    at Socket.listener (/mnt/c/Users/roger/source/onvif/lib/discovery.js:99:3)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage [as onmessage] (dgram.js:921:8) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Wrong SOAP message from 192.168.1.236:60188'
}
```

**Comment by NdiayeeCheikh** [comment]
I have two main onvif problem which are the following ones:
1)
Here is his code from his package (https://www.npmjs.com/package/onvif) and there's no output:
-----------------------------------------------------------------------------------
// @ts-nocheck
import onvif from 'onvif';

console.log('Discovery started');
onvif.Discovery.on('device', function(cam){
// function will be called as soon as NVT responds
	cam.username = "user1";
	cam.password = "user.111";
  console.log('Discovery device', cam);
  cam.connect()
  .then(() => console.log("Connexion réussie !"))  
  .catch(err => console.error("Erreur de connexion:", err));  

});
// Must have an error handler to catch bad replies from the network
onvif.Discovery.on('error', function (err,xml) {
  // function called as soon as NVT responds, but this library could not parse the response
  console.log('Discovery error ' + err);
});
onvif.Discovery.probe(6000); 
-----------------------------------------------------------------------------------
 2) I'm trying to use dgram in order to display available cams in my network because the onvif package from @agsh seems like not working.
Here is the code :
-----------------------------------------------------------------------------------
 import dgram from 'dgram';
import os from 'os';
import axios from 'axios';

const client = dgram.createSocket('udp4');

const multicastAddress = '239.255.255.250';  // Adresse multicast courante pour WS-Discovery (et ONVIF)
const port = 3702;  // Port de découverte (par exemple, 3702 pour WS-Discovery ou ONVIF)

const message = Buffer.from(`
  <?xml version="1.0" encoding="UTF-8"?>
  <Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery">
    <Types>dn:NetworkVideoTransmitter</Types>
    <Scopes />
  </Probe>
`);

// Binding du socket
client.bind(() => {
  // Activer le multicast
  //client.addMembership(multicastAddress);  // S'abonner au groupe multicast
  client.setBroadcast(true);  // Activer le broadcast si nécessaire (pas obligatoire ici)
  console.log("Socket prêt à envoyer et recevoir des messages ");
  
  client.send(message, 0, message.length, port, multicastAddress, (err) => {
    if (err) {
      console.error('Erreur lors de l\'envoi de la requête de découverte:', err);
    } else {
      console.log('Requête de découverte envoyée ');
    }
  });
});

client.on('message', (msg, rinfo) => {
  console.log(`Réponse reçue de ${rinfo.address}:${rinfo.port}`);
  console.log('Message:', msg.toString());
});

client.on('error', (err) => {
  console.log(`Erreur: ${err}`);
  client.close();
});

setTimeout(() => {
  console.log("Fermeture du socket après 10 secondes");
  client.close();
}, 10000);

/*
//Code correcte pour getProfiles
import DigestClient from 'digest-fetch';

async function getOnvifProfiles() {
  const url = 'http://192.168.1.65:80/onvif/device_service';
  const username = 'user1';
  const password = 'user.111';

  const headers = {
    'Content-Type': 'application/soap+xml; charset=utf-8',
    'SOAPAction': '"http://www.onvif.org/ver10/media/wsdl/GetProfiles"'
  };

  const data = `
  <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver10/media/wsdl">
    <soap:Header/>
    <soap:Body>
      <wsdl:GetProfiles/>
    </soap:Body>
  </soap:Envelope>
  `;

  const client = new DigestClient(username, password);

  try {
    const response = await client.fetch(url, {
      method: 'POST',
      headers: headers,
      body: data
    });

    const responseText = await response.text();
    console.log('Réponse du serveur ONVIF:', responseText);
  } catch (error) {
    console.error('Erreur:', error);
  }
}

getOnvifProfiles();
*/
/*
//Code correcte pour getStreamUri
import DigestClient from 'digest-fetch';

async function getOnvifStreamUri() {
  const url = 'http://192.168.1.65:80/onvif/device_service'; // Remplacez par l'URL de votre appareil ONVIF
  const username = 'user1';
  const password = 'user.111';

  const headers = {
    'Content-Type': 'application/soap+xml; charset=utf-8',
    'SOAPAction': '"http://www.onvif.org/ver10/media/wsdl/GetStreamUri"'
  };

  const data = `
  <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver10/media/wsdl">
    <soap:Header/>
    <soap:Body>
      <wsdl:GetStreamUri>
        <wsdl:StreamSetup>
          <tt:Stream>RTP-Unicast</tt:Stream>
          <tt:Transport>
            <tt:Protocol>RTSP</tt:Protocol>
          </tt:Transport>
        </wsdl:StreamSetup>
        <wsdl:ProfileToken>Profile_1</wsdl:ProfileToken>
      </wsdl:GetStreamUri>
    </soap:Body>
  </soap:Envelope>
  `;

  const client = new DigestClient(username, password);

  try {
    const response = await client.fetch(url, {
      method: 'POST',
      headers: headers,
      body: data
    });

    const responseText = await response.text();
    console.log('Réponse du serveur ONVIF (GetStreamUri):', responseText);
  } catch (error) {
    console.error('Erreur:', error);
  }
}

getOnvifStreamUri();
*/

-----------------------------------------------------------------------------------

Here is the ouput when i run it (the code is in the server3.js file):
PS C:\Users\Qwert\my-app\src\app\api\test> node server3.js
Socket prêt à envoyer et recevoir des messages 
Requête de découverte envoyée 
Fermeture du socket après 10 secondes
PS C:\Users\Qwert\my-app\src\app\api\test>
