### ISSUE TITLE
Discovery Node Issue

### ISSUE THREAD

**Issue by Eman457** [agsh/onvif#205]
Hi,
I updated to the latest version and this broke down everything!
The Discovery Node doesn't find cameras any more

**Comment by bartbutenaers** [comment]
Dear @Eman457,,

A few days ago I had a quick look at the discovery code, and it seemed to me that e.g. a NAS (see full description [here](https://github.com/agsh/onvif/issues/204#issuecomment-913093838)) could perhaps cause the discovery to fail.  But not really sure at the moment to be honest...

However today I have installed the latest version of this library, and I also don't get any devices anymore via discovery.  So I have used the new error event handler (as described on the [readme](https://github.com/agsh/onvif#discovery) page), to see what is going wrong.  And then I see this error: `Discovery error Wrong SOAP message from xxxxxx`.  The xxxxx is the IP address from my Onvif camera that was discovered without problems previously.  So this is not the same problem as I had reported in my other issue...

Bart

**Comment by bartbutenaers** [comment]
I want to debug what was going wrong.  So I have repeated the discovery process now a series of times again, and now it works fine every time.  Not sure what went wrong in the beginning...

**Comment by agsh** [comment]
@Eman457 @bartbutenaers Wow, guys, I've looked at discovery module, but didn't saw any changes. Maybe @RogerHardiman can help us?

**Comment by Eman457** [comment]
Hello @bartbutenaers ,
I updated again to a version showing 13hrs at the time I type this and the Discovery Node woke up and shows connected but lost features which were all working before the **git** version. Is there any chance we can go back to the beta before the git version?...

**Comment by bartbutenaers** [comment]
@Eman457,

> the Discovery Node woke up and shows connected but lost features which were all working before the git version

Ah ok you are using my [node-red-contrib-onvif-nodes](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes).  Perhaps it is better if you create a new issue in my repository, because this might be very confusing for Andrew and Roger.  I first need to know if there is an issue with my own code or not...

We will discuss there further ...

> his one errors with "The device has no support for a ptz service"

I assume you are not talking now about Discovery but about PTZ?  If so: yes I updated my git repository to use the latest (0.6.5) version of the agsh/onvif library.  But somebody reported me issues, which were caused by a breaking change (via [this](https://github.com/agsh/onvif/pull/155) pull request): for my old panasonic camera's capabilities where returned, while REolink camera's now have ``undefined` capabilities.  That is hopefully all solved in my Github version.  But the same guy reported that his Discovery doesn't work anymore.  So we need to start searching

@agsh or @RogerHardiman : do you know any way how to troubleshoot discovery issues for other remote users?  Via port forwarding I can connect to remote cams and debug the code without problems.  But I cannot start a discovery from my computer on someone else his LAN?  If you know any tricks, please share those!

**Comment by Eman457** [comment]
Hi @bartbutenaers ,
I have update to yesterday's updated version and can confirm that the features are back! The PTZ nodes are showing green

**Comment by bartbutenaers** [comment]
@Eman457,
Nice to hear that my fix solved it.  Thanks for letting me know!

My last version on Github takes into accounts that - due to the pull request I mentioned above - I need to check the capabilities in multiple ways (as you can see [here](https://github.com/agsh/onvif/issues/207)).
All people that had troubles with their cameras have already reported that things are solved now.  So can you please close this issue?  If you would run into other problems in the future, then please raise an issue on my own Github repository.

Bart

**Comment by Eman457** [comment]
@bartbutenaers ,
Sorry for not closing the issue when I had to but looks good so far.

And thank you.

**Comment by NdiayeeCheikh** [comment]
Hi there ,hope you doing good all of you .
I'm trying to connect to a camera in my local network .But the server is showing me something that i dont undestand when i run "node server.js".
I'm using Nextjs and i'm testing this onvif module in order to integrate it afer :

HERE IS THE ERROR:
Error: read ECONNRESET
at TCP.onStreamRead (node:internal/stream_base_commons:216:20) {
errno: -4077,
code: 'ECONNRESET',
syscall: 'read'
}

AND HERE IS THE FULL CODE:

const server = require('http').createServer((req, res) =>
res.end(`

<script src="/socket.io/socket.io.js"></script><script> const socket = io(), ctx = document.getElementsByTagName('canvas')[0].getContext('2d'); socket.on('data', (data) => { const img = new Image; const url = URL.createObjectURL(new Blob([new Uint8Array(data)], {type: 'application/octet-binary'})); img.onload = () => { URL.revokeObjectURL(url, {type: 'application/octet-binary'}); ctx.drawImage(img, 100, 100); }; img.src = url; }); </script>`)); const { Cam } = require('onvif/promises'), io = require('socket.io')(server), rtsp = require('rtsp-ffmpeg'); server.listen(6147);
const cam = new Cam({username: 'user1', password: 'user.111', hostname: '192.168.1.65', port: 554, timeout: 60000 });
(async() => {
await cam.connect();
const input = (await cam.getStreamUri({protocol:'RTSP'})).uri.replace('://', ://${cam.username}:${cam.password}@);
const input2="rtsp://user1:user.111@192.168.1.65:554/live";
const stream = new rtsp.FFMpeg({input2, resolution: '320x240', quality: 3});
io.on('connection', (socket) => {
const pipeStream = socket.emit.bind(socket, 'data');
stream.on('disconnect', () => stream.removeListener('data', pipeStream)).on('data', pipeStream);
});
setInterval(() => cam.absoluteMove({
x: Math.random() * 2 - 1,
y: Math.random() * 2 - 1,
zoom: Math.random()
}), 3000);
})().catch(console.error);

And by the way , do you know some modules in nodejs , well maintained , allowing the discovery options ?

AND THANKS IN ADVANCES
