### ISSUE TITLE
In Windows system "239.255.255.250" package can not send out with

### ISSUE THREAD

**Issue by goose1005** [agsh/onvif#57]
I follow the probe example and  using Wireshark to watching package, but no "239.2255.255250" package.  it seems windows system block "239.255.255.250" package.

**Comment by goose1005** [comment]
i change multicast address to "239.255.255.200", Wireshark can capture multicast package.

**Comment by RogerHardiman** [comment]
This is probably caused by Windows taking control of 239.255.255.250 for its own purposes.

I believe that to use WS-Discovery under Windows you have to use some Microsoft APIs to tell Windows that your application wants to discover devices on the network. You then tell Windows to do the discovery for you. Windows then sends the discovery packet (the 239.255.255.0 packet) and Windows passes the replies back to your application.

The current code in agsh/onvif does not use the Microsoft API. It use the BSD sockets API which is used by Linux and that can access 239.255.255.250 directly.

I had the same issue in the Raspberry Pi ONVIF Server where I had to write the WS-Discovery service that listens for 239.255.255.250. That code worked on Linux not on Windows.


So someone needs to write (or find) a Node WS-Discovery or SSDP package for Windows.
In ONVIF Device Manager (the source code is on SourceForge.Net) you can see how wrote the software to use the Microsoft Windows APIs so we have open source code to refer to.
